### ISSUE TITLE
Prevents the form from being submitted on Enter key

### ISSUE THREAD

**Issue by cr101** [fitiskin/jquery-autocompleter#1]
We tried to use the plugin on a search form. When pressing the Enter key the form was not being submitted and the callback function was not being fired either.

**Comment by fitiskin** [comment]
Should be fixed by [df97a43a3bb7d081530900741ff25f1dd3016b37](https://github.com/fitiskin/jquery-autocompleter/commit/df97a43a3bb7d081530900741ff25f1dd3016b37)

Forgive me for abandoning the project and answering you a years later.
