### ISSUE TITLE
Using a remote source - how do I format it?

### ISSUE THREAD

**Issue by ghost** [fitiskin/jquery-autocompleter#24]
Hi There!

Im trying to use a remote source for autocompleter, but I am unsure what to return? Do I return <li> html content for each result or a JSON array. If i use a JSON array what should I call the array as there is no longer a way to specify the name as the source becomes the path

Currently the contents of my remote results page looks like this:

var data  =
[
    {
        "hex": "#EFDECD",
        "label": "Almond",
        "rgb": "(239, 222, 205)"
    },
    {
        "hex": "#CD9575",
        "label": "Antique Brass",
        "rgb": "(205, 149, 117)"
    },
    {
        "hex": "#FDD9B5",
        "label": "Apricot",
        "rgb": "(253, 217, 181)"
    },
    {
        "hex": "#78DBE2",
        "label": "Aquamarine",
        "rgb": "(120, 219, 226)"
    }
};

Thanks for any help in advance

**Comment by taeraeyttaejae** [comment]
this project seems quite a lot like it has been abandoned.

**Comment by fitiskin** [comment]
I'm sorry that I abandoned the project. Your example should work out of the box.
Also you can use new option named "format" to map values as mentioned [here](https://github.com/fitiskin/jquery-autocompleter/pull/39#issuecomment-1088778480).
