### ISSUE TITLE
Appends undefined on the end of the results list in IE8

### ISSUE THREAD

**Issue by cr101** [fitiskin/jquery-autocompleter#3]
Solution: Need to do a check if the label is not empty on Line 388

**Comment by fitiskin** [comment]
Should be fixed by [df97a43a3bb7d081530900741ff25f1dd3016b37](https://github.com/fitiskin/jquery-autocompleter/commit/df97a43a3bb7d081530900741ff25f1dd3016b37)

Forgive me for abandoning the project and answering you a years later.
