### ISSUE TITLE
TypeError: Cannot read property 'toUpperCase' of undefined

### ISSUE THREAD

**Issue by stelasido** [fitiskin/jquery-autocompleter#34]
This error is with your example from the docs with the `data` source. The error is for this code:

`switch (i) {
              case 0:
                if (label.toUpperCase().search(query) === 0) {`

In the function:

`  /**
   * @method private
   * @name _search
   * @description Local search function, return best collation
   * @param query [string] "Query string"
   * @param source [object] "Source data"
   * @param data [object] "Instance data"
   */
  function _search(query, source, data) {`

I am using simple code from your docs:

`    const input = $('.input-class');

    var data = [
        { value: 1, label: 'one' },
        { value: 2, label: 'two' },
        { value: 3, label: 'three' }
    ];
    input.autocompleter({ source: data });`

I have that input with that class. The script is loaded after all the HTML.

**Comment by fitiskin** [comment]
Forgive me for abandoning the project and answering you a few years later.

Can't reproduce it. Working example: https://codesandbox.io/s/jquery-autocompleter-bo16h1?file=/src/index.js
