### ISSUE TITLE
Uncaught TypeError: Cannot read property 'length' of null

### ISSUE THREAD

**Issue by stelasido** [fitiskin/jquery-autocompleter#35]
I am using the second example `Autocompleter for the first name input with caching`. Exact same example and I am getting this error:

> Uncaught TypeError: Cannot read property 'length' of null 
For this code:

`if (source.length) {`

For this function:

`  /**
   * @method private
   * @name _search
   * @description Local search function, return best collation
   * @param query [string] "Query string"
   * @param source [object] "Source data"
   * @param data [object] "Instance data"
   */
  function _search(query, source, data) {`

Is this library maintained ?
All of your examples doesn't work. The problem is not in my code. I have loaded jQuery. All the script is loaded after HTML.

I have tried with `src` and `dist` folders and it is tthe same.

**Comment by fitiskin** [comment]
Forgive me for abandoning the project and answering you a few years later.

I have updated the example. It was supposed to use the "source" option to pass remote URL, for example:

```javascript
$(function () {
  $("#nope").autocompleter({
    source: "https://api.publicapis.org/entries",
    combine: function (params) {
      return {
        title: params.query,
      };
    },
    format: function (data) {
      return data.entries.map((entry) => ({
        label: entry.API,
      }));
    },
  });
});
```
