### ISSUE TITLE
clicking Scrollbar closing list

### ISSUE THREAD

**Issue by glauberpincus** [fitiskin/jquery-autocompleter#47]
Hi,
Your autocompleter is working wonders..
I just have an issue. I added a max-height to the UL container and added overflow:auto. When I click on the **scrollbar** of the suggestion container (UL) it causes the list to close and therefore it will trigger a blur/change event. All I wanted it to scroll to one of the suggestions.

All other methods works very nice: Keyboard navigation, mouse click on item, tapping from a Laptop, or mobile device.

If you can help with this issue. i will be glad to pay you for that.

**Comment by fitiskin** [comment]
Hi @glauberpincus

Are you having a problem with macOS? Maybe it is supposed to work this way. I see the main page scroll, which likewise does not register a click on itself until it switches to the "scroll mode".

![Screen Recording 2022-10-09 at 21 02 26](https://user-images.githubusercontent.com/5507542/194772639-24dcc0c0-0e55-4650-a592-26d19e7dada1.gif)

You can get around the problem by adding a tiny right padding to `.autocompleter-list` element.

Make sure using latest version. Hope it helps!

**Comment by fitiskin** [comment]
Feel free to reopen
